# Generated by Django 4.0.3 on 2022-04-21 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0002_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_description', models.CharField(max_length=200)),
                ('reward_points', models.IntegerField()),
                ('reward_status', models.BooleanField(default=True)),
                ('reward_created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_updated_at', models.DateTimeField(auto_now=True)),
                ('reward_deleted_at', models.DateTimeField(auto_now=True)),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_book_name', to='crud.books')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward',
            },
        ),
    ]
